# Generated by Django 6.0.7 on 2026-07-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telegramuser_is_premium_telegramuser_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='task',
        ),
        migrations.RemoveField(
            model_name='message',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stage',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
