# Generated by Django 6.0.7 on 2026-07-25 15:24

from django.conf import settings
from django.db import migrations
from django.db import models


def copy_legacy_members(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    ProjectMembership = apps.get_model('core', 'ProjectMembership')
    database = schema_editor.connection.alias

    for project in Project.objects.using(database).all().iterator():
        legacy_member_ids = list(
            project.members.using(database).values_list('pk', flat=True)
        )
        owner_membership, _created = ProjectMembership.objects.using(
            database
        ).get_or_create(
            project_id=project.pk,
            user_id=project.owner_id,
            defaults={'role': 'owner'},
        )
        if owner_membership.role != 'owner':
            owner_membership.role = 'owner'
            owner_membership.save(update_fields=['role'])

        for user_id in legacy_member_ids:
            ProjectMembership.objects.using(database).get_or_create(
                project_id=project.pk,
                user_id=user_id,
                defaults={
                    'role': 'owner' if user_id == project.owner_id else 'member'
                },
            )


def restore_legacy_members(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    ProjectMembership = apps.get_model('core', 'ProjectMembership')
    database = schema_editor.connection.alias

    for project in Project.objects.using(database).all().iterator():
        member_ids = ProjectMembership.objects.using(database).filter(
            project_id=project.pk
        ).values_list('user_id', flat=True)
        project.members.add(*member_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_discussion_message'),
    ]

    operations = [
        migrations.RunPython(copy_legacy_members, restore_legacy_members),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(
                blank=True,
                related_name='projects',
                through='core.ProjectMembership',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
