"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env лежит рядом с manage.py и НЕ коммитится в git (см. .gitignore).
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Токен бота от @BotFather — нужен для проверки подписи initData (core/telegram_auth.py)
TELEGRAM_BOT_TOKEN = os.environ['TELEGRAM_BOT_TOKEN']

# Используется в Django admin для полной ссылки-приглашения. В production
# берётся существующий APP_DOMAIN; локально остаётся относительная ссылка.
_app_domain = os.environ.get('APP_DOMAIN', '').strip()
INVITE_BASE_URL = os.environ.get('INVITE_BASE_URL', '').rstrip('/') or (
    f'https://{_app_domain}' if _app_domain else ''
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_htmx',

    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Добавляет request.htmx — булев объект с атрибутами (request.htmx.boosted
    # и т.д.), чтобы во view отличать полный запрос от партиала HTMX.
    'django_htmx.middleware.HtmxMiddleware',
]
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# Кастомная модель пользователя. ОБЯЗАТЕЛЬНО указывается до первой миграции —
# после того как таблицы созданы, сменить AUTH_USER_MODEL штатно нельзя.
AUTH_USER_MODEL = 'core.TelegramUser'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.dev_accounts',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.environ.get('DATABASE_PATH', BASE_DIR / 'db.sqlite3')),
        'OPTIONS': {
            'timeout': int(os.environ.get('SQLITE_TIMEOUT', '30')),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

# Важно для корректной работы дедлайнов/уведомлений — иначе Django будет
# сравнивать deadline с текущим временем в UTC, и "уведомление за час
# до дедлайна" может улететь на 3 часа раньше или позже.
TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}


# ---------------------------------------------------------------------------
# Telegram Mini App: страница открывается внутри Telegram (в вебе и на
# десктопе — буквально во вложенном iframe), поэтому два дефолтных
# защитных механизма Django нужно осознанно ослабить именно под этот случай:
# ---------------------------------------------------------------------------

# 1) По умолчанию Django шлёт X-Frame-Options: DENY и браузер откажется
#    рендерить страницу во фрейме Telegram. Разрешаем embedding.
X_FRAME_OPTIONS = 'ALLOWALL'

# 2) Cookie сессии/CSRF выставляются с нашего домена, но браузер видит их
#    в контексте чужого документа (telegram.org), т.е. это third-party
#    context. SameSite=Lax (дефолт Django) такие куки на POST-запросы
#    из iframe может резать. SameSite=None требует Secure=True (HTTPS),
#    поэтому включаем это вне DEBUG — на VPS у нас будет HTTPS. Для локальной
#    проверки через HTTPS-туннель задайте TELEGRAM_SECURE_COOKIES=True в .env.
TELEGRAM_SECURE_COOKIES = (
    not DEBUG or os.environ.get('TELEGRAM_SECURE_COOKIES', 'False') == 'True'
)
if TELEGRAM_SECURE_COOKIES:
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True

# 3) Домены, с которых Django принимает POST с проверкой CSRF (Origin-заголовок
#    должен совпадать). Заполним реальным доменом на этапе деплоя;
#    туда же добавим https://<ngrok-адрес> на время локального теста.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# Production traffic terminates TLS at Caddy and reaches Django over the
# internal Docker network. Trust only Caddy's standard forwarded-proto header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = (
    not DEBUG or os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
