"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env лежит рядом с manage.py и НЕ коммитится в git (см. .gitignore).
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Токен бота от @BotFather — нужен для проверки подписи initData (core/telegram_auth.py)
TELEGRAM_BOT_TOKEN = os.environ['TELEGRAM_BOT_TOKEN']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_htmx',

    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Добавляет request.htmx — булев объект с атрибутами (request.htmx.boosted
    # и т.д.), чтобы во view отличать полный запрос от партиала HTMX.
    'django_htmx.middleware.HtmxMiddleware',
]

# Кастомная модель пользователя. ОБЯЗАТЕЛЬНО указывается до первой миграции —
# после того как таблицы созданы, сменить AUTH_USER_MODEL штатно нельзя.
AUTH_USER_MODEL = 'core.TelegramUser'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

# Важно для корректной работы дедлайнов/уведомлений — иначе Django будет
# сравнивать deadline с текущим временем в UTC, и "уведомление за час
# до дедлайна" может улететь на 3 часа раньше или позже.
TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# ---------------------------------------------------------------------------
# Telegram Mini App: страница открывается внутри Telegram (в вебе и на
# десктопе — буквально во вложенном iframe), поэтому два дефолтных
# защитных механизма Django нужно осознанно ослабить именно под этот случай:
# ---------------------------------------------------------------------------

# 1) По умолчанию Django шлёт X-Frame-Options: DENY и браузер откажется
#    рендерить страницу во фрейме Telegram. Разрешаем embedding.
X_FRAME_OPTIONS = 'ALLOWALL'

# 2) Cookie сессии/CSRF выставляются с нашего домена, но браузер видит их
#    в контексте чужого документа (telegram.org), т.е. это third-party
#    context. SameSite=Lax (дефолт Django) такие куки на POST-запросы
#    из iframe может резать. SameSite=None требует Secure=True (HTTPS),
#    поэтому включаем это только вне DEBUG — на VPS у нас будет HTTPS
#    (Шаг деплоя), а локально Mini App тестируется через https-туннель
#    (ngrok), где эти настройки тоже нужно будет включить руками.
if not DEBUG:
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True

# 3) Домены, с которых Django принимает POST с проверкой CSRF (Origin-заголовок
#    должен совпадать). Заполним реальным доменом на этапе деплоя;
#    туда же добавим https://<ngrok-адрес> на время локального теста.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]
