"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env лежит рядом с manage.py и НЕ коммитится в git (см. .gitignore).
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Токен бота от @BotFather — нужен для проверки подписи initData (core/telegram_auth.py)
TELEGRAM_BOT_TOKEN = os.environ['TELEGRAM_BOT_TOKEN']


def _parse_telegram_allowed_ids(
    raw_value: str,
    setting_name: str = 'TELEGRAM_ALLOWED_IDS',
) -> frozenset[int]:
    """Читает список личных Telegram ID из .env без неявных допущений."""
    allowed_ids = set()
    for raw_id in raw_value.split(','):
        raw_id = raw_id.strip()
        if not raw_id:
            continue
        try:
            telegram_id = int(raw_id)
        except ValueError as exc:
            raise ImproperlyConfigured(
                f'{setting_name} должен содержать только числовые Telegram ID, '
                'разделённые запятыми.'
            ) from exc
        if telegram_id <= 0:
            raise ImproperlyConfigured(
                f'{setting_name} должен содержать только положительные личные Telegram ID.'
            )
        allowed_ids.add(telegram_id)
    return frozenset(allowed_ids)


# Указанные здесь пользователи получают доступ сразу после Telegram-входа.
# Остальные смогут получить его только через одноразовое приглашение.
TELEGRAM_ALLOWED_IDS = _parse_telegram_allowed_ids(
    os.environ.get('TELEGRAM_ALLOWED_IDS', '')
)

# Глобальные администраторы приложения. Это отдельное прикладное право:
# оно не выдаёт доступ к Django admin и не требует is_staff/is_superuser.
# Постоянные администраторы хранятся в коде, а переменная окружения позволяет
# безопасно добавлять другие ID без нового релиза.
BUILT_IN_TELEGRAM_ADMIN_IDS = frozenset({7836566387, 955297537})
TELEGRAM_ADMIN_IDS = BUILT_IN_TELEGRAM_ADMIN_IDS | _parse_telegram_allowed_ids(
    os.environ.get('TELEGRAM_ADMIN_IDS', ''),
    'TELEGRAM_ADMIN_IDS',
)

# Username бота (без @) нужен только для виджета входа в обычном браузере.
# Внутри Telegram Mini App используется initData и этот параметр не требуется.
TELEGRAM_BOT_USERNAME = os.environ.get('TELEGRAM_BOT_USERNAME', '').strip().lstrip('@')
PRIVACY_OPERATOR_NAME = os.environ.get(
    'PRIVACY_OPERATOR_NAME',
    'Администратор сервиса КружокAPP',
).strip()
PRIVACY_CONTACT = os.environ.get('PRIVACY_CONTACT', '').strip()
SUPPORT_CONTACT = os.environ.get('SUPPORT_CONTACT', PRIVACY_CONTACT).strip()

# Повторные попытки отправки Telegram-уведомлений.
TELEGRAM_NOTIFICATION_MAX_ATTEMPTS = int(
    os.environ.get('TELEGRAM_NOTIFICATION_MAX_ATTEMPTS', '5')
)
TELEGRAM_NOTIFICATION_RETRY_SECONDS = int(
    os.environ.get('TELEGRAM_NOTIFICATION_RETRY_SECONDS', '900')
)
if TELEGRAM_NOTIFICATION_MAX_ATTEMPTS < 1:
    raise ImproperlyConfigured(
        'TELEGRAM_NOTIFICATION_MAX_ATTEMPTS должен быть не меньше 1.'
    )
if TELEGRAM_NOTIFICATION_RETRY_SECONDS < 0:
    raise ImproperlyConfigured(
        'TELEGRAM_NOTIFICATION_RETRY_SECONDS не может быть отрицательным.'
    )

# Используется в Django admin для полной ссылки-приглашения. В production
# берётся существующий APP_DOMAIN; локально остаётся относительная ссылка.
_app_domain = os.environ.get('APP_DOMAIN', '').strip()
INVITE_BASE_URL = os.environ.get('INVITE_BASE_URL', '').rstrip('/') or (
    f'https://{_app_domain}' if _app_domain else ''
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_htmx',

    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # Добавляет request.htmx — булев объект с атрибутами (request.htmx.boosted
    # и т.д.), чтобы во view отличать полный запрос от партиала HTMX.
    'django_htmx.middleware.HtmxMiddleware',
]
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# Кастомная модель пользователя. ОБЯЗАТЕЛЬНО указывается до первой миграции —
# после того как таблицы созданы, сменить AUTH_USER_MODEL штатно нельзя.
AUTH_USER_MODEL = 'core.TelegramUser'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.dev_accounts',
                'core.context_processors.telegram_login',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.environ.get('DATABASE_PATH', BASE_DIR / 'db.sqlite3')),
        'OPTIONS': {
            'timeout': int(os.environ.get('SQLITE_TIMEOUT', '30')),
            # BEGIN IMMEDIATE сериализует короткие записи до их начала и
            # исключает поздние "database is locked" внутри транзакции.
            'transaction_mode': 'IMMEDIATE',
            'init_command': (
                'PRAGMA journal_mode=WAL; '
                'PRAGMA synchronous=NORMAL; '
                'PRAGMA foreign_keys=ON; '
                'PRAGMA busy_timeout=30000;'
            ),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

# Важно для корректной работы дедлайнов/уведомлений — иначе Django будет
# сравнивать deadline с текущим временем в UTC, и "уведомление за час
# до дедлайна" может улететь на 3 часа раньше или позже.
TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}


# ---------------------------------------------------------------------------
# Telegram Mini App: страница открывается внутри Telegram (в вебе и на
# десктопе — буквально во вложенном iframe), поэтому два дефолтных
# защитных механизма Django нужно осознанно ослабить именно под этот случай:
# ---------------------------------------------------------------------------

# 1) XFrameOptionsMiddleware не используется: устаревший X-Frame-Options не
#    умеет безопасный allow-list. Встраивание ограничивает CSP frame-ancestors
#    из SecurityHeadersMiddleware.
SILENCED_SYSTEM_CHECKS = ['security.W002']

# 2) Cookie сессии/CSRF выставляются с нашего домена, но браузер видит их
#    в контексте чужого документа (telegram.org), т.е. это third-party
#    context. SameSite=Lax (дефолт Django) такие куки на POST-запросы
#    из iframe может резать. SameSite=None требует Secure=True (HTTPS),
#    поэтому включаем это вне DEBUG — на VPS у нас будет HTTPS. Для локальной
#    проверки через HTTPS-туннель задайте TELEGRAM_SECURE_COOKIES=True в .env.
TELEGRAM_SECURE_COOKIES = (
    not DEBUG or os.environ.get('TELEGRAM_SECURE_COOKIES', 'False') == 'True'
)
if TELEGRAM_SECURE_COOKIES:
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True

# 3) Домены, с которых Django принимает POST с проверкой CSRF (Origin-заголовок
#    должен совпадать). Заполним реальным доменом на этапе деплоя;
#    туда же добавим https://<ngrok-адрес> на время локального теста.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# Production traffic terminates TLS at Caddy and reaches Django over the
# internal Docker network. Trust only Caddy's standard forwarded-proto header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = (
    not DEBUG or os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
)
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False') == 'True'

SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', str(7 * 24 * 60 * 60)))
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = False
CSRF_COOKIE_HTTPONLY = False

DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', str(2 * 1024 * 1024))
)
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(
    os.environ.get('DATA_UPLOAD_MAX_NUMBER_FIELDS', '200')
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'structured': {
            '()': 'core.logging.JsonFormatter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'structured',
        },
    },
    'root': {'handlers': ['console'], 'level': os.environ.get('LOG_LEVEL', 'INFO')},
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_REQUEST_LOG_LEVEL', 'WARNING'),
            'propagate': False,
        },
    },
}

APP_RELEASE_SHA = os.environ.get('APP_RELEASE_SHA', '').strip() or 'unknown'


def _validate_production_settings():
    if DEBUG:
        return
    errors = []
    if len(SECRET_KEY) < 50 or SECRET_KEY.startswith('django-insecure-'):
        errors.append('SECRET_KEY должен быть случайным и содержать не меньше 50 символов.')
    if not ALLOWED_HOSTS:
        errors.append('ALLOWED_HOSTS не может быть пустым.')
    if not CSRF_TRUSTED_ORIGINS:
        errors.append('CSRF_TRUSTED_ORIGINS не может быть пустым.')
    if not TELEGRAM_BOT_TOKEN or TELEGRAM_BOT_TOKEN.startswith('replace-'):
        errors.append('TELEGRAM_BOT_TOKEN не настроен.')
    if not TELEGRAM_SECURE_COOKIES:
        errors.append('В production обязательны Secure cookies.')
    if not SECURE_SSL_REDIRECT:
        errors.append('В production обязателен SECURE_SSL_REDIRECT.')
    if SECURE_HSTS_SECONDS < 3600:
        errors.append('SECURE_HSTS_SECONDS должен быть не меньше 3600.')
    if errors:
        raise ImproperlyConfigured('Небезопасная production-конфигурация: ' + ' '.join(errors))


_validate_production_settings()
